cleanup

diff --git a/bin/upload_to_s3 b/bin/upload_to_s3
--- a/bin/upload_to_s3
+++ b/bin/upload_to_s3
@@ -27,7 +27,14 @@ get_files_list () {
     # Include all template files
     FILES=`find . -maxdepth 1 -name "*.template" | xargs basename`
     for FILE in $FILES; do
-        FILES_LIST=(${FILES_LIST[@]} $FILE)
+        echo -n "$FILE Valid: "
+        aws cloudformation validate-template --template-body file://$FILE > /dev/null
+        if [ "$?" = "0" ]; then
+          echo "ok"
+          FILES_LIST=(${FILES_LIST[@]} $FILE)
+        else
+          echo "failed"
+        fi
     done
 }
 
